// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: promotion/promotion_service.proto

package promotion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromotionService_ApplyPromotion_FullMethodName  = "/promotion.PromotionService/ApplyPromotion"
	PromotionService_VerifyPromotion_FullMethodName = "/promotion.PromotionService/VerifyPromotion"
)

// PromotionServiceClient is the client API for PromotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromotionServiceClient interface {
	ApplyPromotion(ctx context.Context, in *ApplyPromotionRequest, opts ...grpc.CallOption) (*ApplyPromotionResponse, error)
	VerifyPromotion(ctx context.Context, in *VerifyPromotionRequest, opts ...grpc.CallOption) (*VerifyPromotionResponse, error)
}

type promotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionServiceClient(cc grpc.ClientConnInterface) PromotionServiceClient {
	return &promotionServiceClient{cc}
}

func (c *promotionServiceClient) ApplyPromotion(ctx context.Context, in *ApplyPromotionRequest, opts ...grpc.CallOption) (*ApplyPromotionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPromotionResponse)
	err := c.cc.Invoke(ctx, PromotionService_ApplyPromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) VerifyPromotion(ctx context.Context, in *VerifyPromotionRequest, opts ...grpc.CallOption) (*VerifyPromotionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPromotionResponse)
	err := c.cc.Invoke(ctx, PromotionService_VerifyPromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServiceServer is the server API for PromotionService service.
// All implementations must embed UnimplementedPromotionServiceServer
// for forward compatibility.
type PromotionServiceServer interface {
	ApplyPromotion(context.Context, *ApplyPromotionRequest) (*ApplyPromotionResponse, error)
	VerifyPromotion(context.Context, *VerifyPromotionRequest) (*VerifyPromotionResponse, error)
	mustEmbedUnimplementedPromotionServiceServer()
}

// UnimplementedPromotionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromotionServiceServer struct{}

func (UnimplementedPromotionServiceServer) ApplyPromotion(context.Context, *ApplyPromotionRequest) (*ApplyPromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPromotion not implemented")
}
func (UnimplementedPromotionServiceServer) VerifyPromotion(context.Context, *VerifyPromotionRequest) (*VerifyPromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPromotion not implemented")
}
func (UnimplementedPromotionServiceServer) mustEmbedUnimplementedPromotionServiceServer() {}
func (UnimplementedPromotionServiceServer) testEmbeddedByValue()                          {}

// UnsafePromotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionServiceServer will
// result in compilation errors.
type UnsafePromotionServiceServer interface {
	mustEmbedUnimplementedPromotionServiceServer()
}

func RegisterPromotionServiceServer(s grpc.ServiceRegistrar, srv PromotionServiceServer) {
	// If the following call pancis, it indicates UnimplementedPromotionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromotionService_ServiceDesc, srv)
}

func _PromotionService_ApplyPromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).ApplyPromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_ApplyPromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).ApplyPromotion(ctx, req.(*ApplyPromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_VerifyPromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).VerifyPromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_VerifyPromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).VerifyPromotion(ctx, req.(*VerifyPromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromotionService_ServiceDesc is the grpc.ServiceDesc for PromotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promotion.PromotionService",
	HandlerType: (*PromotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyPromotion",
			Handler:    _PromotionService_ApplyPromotion_Handler,
		},
		{
			MethodName: "VerifyPromotion",
			Handler:    _PromotionService_VerifyPromotion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promotion/promotion_service.proto",
}
