apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: promotion
  name: promotion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promotion
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: promotion
    spec:
      containers:
      - env:
        - name: ORDER_GRPC_HOST
          value: order
        - name: PROMOTION_GRPC_HOST
          value: promotion
        envFrom:
        - configMapRef:
            name: env-dev
        image: fbin243/ztf-promotion:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        name: ztf-promotion
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 50551
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
