global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
- job_name: 'ztf-order'
  static_configs:
  - targets: [ 'ztf-order:8080' ]
- job_name: 'ztf-promotion'
  static_configs:
  - targets: [ 'ztf-promotion:8081' ]
