// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order/order_msg.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserRequest) Reset() {
	*x = ValidateUserRequest{}
	mi := &file_order_order_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserRequest) ProtoMessage() {}

func (x *ValidateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserRequest.ProtoReflect.Descriptor instead.
func (*ValidateUserRequest) Descriptor() ([]byte, []int) {
	return file_order_order_msg_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ValidateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserResponse) Reset() {
	*x = ValidateUserResponse{}
	mi := &file_order_order_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserResponse) ProtoMessage() {}

func (x *ValidateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserResponse.ProtoReflect.Descriptor instead.
func (*ValidateUserResponse) Descriptor() ([]byte, []int) {
	return file_order_order_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateUserResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_order_order_msg_proto protoreflect.FileDescriptor

const file_order_order_msg_proto_rawDesc = "" +
	"\n" +
	"\x15order/order_msg.proto\x12\tpromotion\".\n" +
	"\x13ValidateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\",\n" +
	"\x14ValidateUserResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05validB\x1cZ\x1aztf-backend/proto/pb/orderb\x06proto3"

var (
	file_order_order_msg_proto_rawDescOnce sync.Once
	file_order_order_msg_proto_rawDescData []byte
)

func file_order_order_msg_proto_rawDescGZIP() []byte {
	file_order_order_msg_proto_rawDescOnce.Do(func() {
		file_order_order_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_msg_proto_rawDesc), len(file_order_order_msg_proto_rawDesc)))
	})
	return file_order_order_msg_proto_rawDescData
}

var file_order_order_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_order_msg_proto_goTypes = []any{
	(*ValidateUserRequest)(nil),  // 0: promotion.ValidateUserRequest
	(*ValidateUserResponse)(nil), // 1: promotion.ValidateUserResponse
}
var file_order_order_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_order_msg_proto_init() }
func file_order_order_msg_proto_init() {
	if File_order_order_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_msg_proto_rawDesc), len(file_order_order_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_order_msg_proto_goTypes,
		DependencyIndexes: file_order_order_msg_proto_depIdxs,
		MessageInfos:      file_order_order_msg_proto_msgTypes,
	}.Build()
	File_order_order_msg_proto = out.File
	file_order_order_msg_proto_goTypes = nil
	file_order_order_msg_proto_depIdxs = nil
}
