// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order/order_service.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_order_service_proto protoreflect.FileDescriptor

const file_order_order_service_proto_rawDesc = "" +
	"\n" +
	"\x19order/order_service.proto\x12\tpromotion\x1a\x15order/order_msg.proto2_\n" +
	"\fOrderService\x12O\n" +
	"\fValidateUser\x12\x1e.promotion.ValidateUserRequest\x1a\x1f.promotion.ValidateUserResponseB\x1cZ\x1aztf-backend/proto/pb/orderb\x06proto3"

var file_order_order_service_proto_goTypes = []any{
	(*ValidateUserRequest)(nil),  // 0: promotion.ValidateUserRequest
	(*ValidateUserResponse)(nil), // 1: promotion.ValidateUserResponse
}
var file_order_order_service_proto_depIdxs = []int32{
	0, // 0: promotion.OrderService.ValidateUser:input_type -> promotion.ValidateUserRequest
	1, // 1: promotion.OrderService.ValidateUser:output_type -> promotion.ValidateUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_order_service_proto_init() }
func file_order_order_service_proto_init() {
	if File_order_order_service_proto != nil {
		return
	}
	file_order_order_msg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_service_proto_rawDesc), len(file_order_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_service_proto_goTypes,
		DependencyIndexes: file_order_order_service_proto_depIdxs,
	}.Build()
	File_order_order_service_proto = out.File
	file_order_order_service_proto_goTypes = nil
	file_order_order_service_proto_depIdxs = nil
}
